"""Writing Agent – composes a research paper from experiment results."""

from __future__ import annotations

import os
import re
import subprocess
from pathlib import Path
from typing import Any, Optional

from ai_research_agent.agents.base import BaseAgent
from ai_research_agent.models.common import ProjectStatus
from ai_research_agent.models.experiment import ExperimentOutput
from ai_research_agent.models.paper import (
    Citation,
    PaperDraft,
    PaperDraftStatus,
    PaperSection,
    WritingOutput,
)
from ai_research_agent.models.plan import PlanningOutput
from ai_research_agent.models.proposal import CandidateIdea, IdeationOutput
from ai_research_agent.tools.filesystem import atomic_write, write_json


# ACL/ICML-style LaTeX template
_LATEX_TEMPLATE = r"""\documentclass[10pt,a4paper]{{article}}
\usepackage[utf8]{{inputenc}}
\usepackage[T1]{{fontenc}}
\usepackage{{amsmath,amssymb,amsfonts}}
\usepackage{{graphicx}}
\usepackage{{hyperref}}
\usepackage{{booktabs}}
\usepackage{{url}}
\usepackage{{enumitem}}

\title{{{title}}}

\author{{
  AI Research Agent$^{1}$\footnote{{Generated by AI Research Agent pipeline}}\\%
  \\%
  $^{1}${{Autonomous Research System}}\\%
}}

\date{{\today}}

\begin{{document}}

\maketitle

\begin{{abstract}}
{abstract}
\end{{abstract}}

\section*{{Introduction}}
{introduction}

\section*{{Related Work}}
{related_work}

\section*{{Methodology}}
{methodology}

\section*{{Experiments}}
{experiments}

\section*{{Results}}
{results}

\section*{{Discussion}}
{discussion}

\section*{{Conclusion}}
{conclusion}

\section*{{References}}

\end{{document}}
"""


class WritingAgent(BaseAgent):
    """Composes a full research paper draft from ideation and experiment outputs."""

    agent_status = ProjectStatus.WRITING

    def __init__(
        self,
        project: Any,
        ideation_output: IdeationOutput,
        planning_output: PlanningOutput,
        experiment_output: ExperimentOutput,
    ) -> None:
        super().__init__(project)
        self.ideation_output = ideation_output
        self.planning_output = planning_output
        self.experiment_output = experiment_output

    def run(self) -> WritingOutput:
        self.project.update_status(
            status=ProjectStatus.WRITING,
            current_agent=self.name,
            step="generating paper content",
        )

        # Get idea
        idea = self._get_idea()

        # Generate sections
        sections = self._generate_sections(idea)

        # Generate citations
        citations = self._generate_citations(idea)

        # Generate results tables
        tables = self._generate_tables()

        # Generate LaTeX source
        latex_source = self._generate_latex(sections, citations, idea)

        # Quality checks
        quality_checks = self._run_quality_checks(latex_source, tables, citations)

        # Compile PDF (if possible)
        pdf_path = self._compile_pdf(latex_source)

        # Generate markdown version
        md_content = self._generate_markdown(sections, tables, citations)

        draft = PaperDraft(
            title=idea.title if idea else "Untitled Research Paper",
            abstract=self._generate_abstract(idea),
            authors=["AI Research Agent"],
            sections=sections,
            citations=citations,
            draft_status=PaperDraftStatus.DRAFT,
            latex_source=latex_source,
            pdf_path=pdf_path,
        )

        output = WritingOutput(
            idea_title=idea.title if idea else "Unknown",
            draft=draft,
            review_comments=self._generate_review_comments(quality_checks),
            revision_notes="Generated paper - requires human review",
            quality_checks_passed=quality_checks,
        )

        # Write outputs
        latex_path = self.project.writing_dir / "paper.tex"
        self._log("atomic_write", {"path": str(latex_path)})
        atomic_write(latex_path, latex_source)

        md_path = self.project.writing_dir / "paper.md"
        atomic_write(md_path, md_content)

        out_path = self.project.writing_dir / "writing_output.json"
        write_json(out_path, output.model_dump())

        return output

    def _get_idea(self) -> CandidateIdea:
        """Get the selected idea from ideation output."""
        if self.ideation_output.selected_idea:
            return self.ideation_output.selected_idea
        if self.ideation_output.candidate_ideas:
            return self.ideation_output.candidate_ideas[0]
        raise ValueError("No candidate idea available")

    def _generate_abstract(self, idea: CandidateIdea) -> str:
        """Generate abstract section."""
        hypothesis = idea.hypothesis if idea else "N/A"
        novelty = idea.novelty_justification if idea else "N/A"

        # Extract metrics from experiment results
        main_result = self.experiment_output.results[0] if self.experiment_output.results else None
        accuracy_str = ""
        if main_result:
            accuracy_str = f" Our method achieves {main_result.mean:.1%} accuracy (±{main_result.std:.1%})"

        return (
            f"We investigate {hypothesis}. "
            f"{novelty}.{accuracy_str} "
            f"Experiments across multiple datasets demonstrate the effectiveness of our approach."
        )

    def _generate_sections(self, idea: CandidateIdea) -> list[PaperSection]:
        """Generate all paper sections."""
        sections = []

        # Introduction
        intro_content = f"""
This paper investigates {idea.hypothesis}.

\textbf{{Motivation}}. {idea.motivation}

\textbf{{Hypothesis}}. {idea.hypothesis_binary}

\textbf{{Contributions}}.
1. We propose a novel method for {idea.title}.
2. We conduct extensive experiments demonstrating effectiveness.
3. We provide comprehensive ablation studies.

The remainder of this paper is organized as follows. Section 2 reviews related work. Section 3 describes our methodology. Section 4 presents experimental results. Section 5 discusses findings. Section 6 concludes.
"""
        sections.append(
            PaperSection(
                name="Introduction",
                content=intro_content,
                word_count=len(intro_content.split()),
            )
        )

        # Related Work
        rw_content = self._generate_related_work(idea)
        sections.append(
            PaperSection(
                name="Related Work",
                content=rw_content,
                word_count=len(rw_content.split()),
            )
        )

        # Methodology
        method_content = self._generate_methodology(idea)
        sections.append(
            PaperSection(
                name="Methodology",
                content=method_content,
                word_count=len(method_content.split()),
            )
        )

        # Experiments
        exp_content = self._generate_experiments()
        sections.append(
            PaperSection(
                name="Experiments",
                content=exp_content,
                word_count=len(exp_content.split()),
            )
        )

        # Results
        results_content = self._generate_results()
        sections.append(
            PaperSection(
                name="Results",
                content=results_content,
                word_count=len(results_content.split()),
            )
        )

        # Discussion
        disc_content = self._generate_discussion()
        sections.append(
            PaperSection(
                name="Discussion",
                content=disc_content,
                word_count=len(disc_content.split()),
            )
        )

        # Conclusion
        conc_content = self._generate_conclusion()
        sections.append(
            PaperSection(
                name="Conclusion",
                content=conc_content,
                word_count=len(conc_content.split()),
            )
        )

        return sections

    def _generate_related_work(self, idea: CandidateIdea) -> str:
        """Generate related work section from ideation output."""
        content = ""

        if idea.related_work:
            for rw in idea.related_work[:5]:
                authors = ", ".join(rw.authors[:3]) if rw.authors else "Unknown"
                year = rw.year or "N/A"
                content += f"\\textbf{{{authors} ({year})}}. {rw.summary}\n\n"

        if not content:
            content = "Previous work in this area includes foundational approaches by..."

        return content

    def _generate_methodology(self, idea: CandidateIdea) -> str:
        """Generate methodology section from planning output."""
        plan = self.planning_output.plan
        hyperparams = self.planning_output.hyperparameters

        content = f"""
### Problem Definition

Given {plan.objective}, we formulate this as a supervised learning problem.

### Proposed Method

Our approach builds on {plan.proposed_method}. The key innovations include:

1. Novel architecture design
2. Improved training procedure
3. Effective regularization

\subsection*{{Architecture}}

We use a neural network with hidden layer sizes {hyperparams.get('hidden_dims', [256, 128])}.

\subsection*{{Training}}

We train with Adam optimizer (lr={hyperparams.get('learning_rate', 0.001)}, weight\_decay={hyperparams.get('weight_decay', 0.0001)})
for {hyperparams.get('epochs', 50)} epochs with batch size {hyperparams.get('batch_size', 128)}.

We use {hyperparams.get('scheduler', 'cosine_annealing')} learning rate schedule.
"""

        return content

    def _generate_experiments(self) -> str:
        """Generate experiments section."""
        plan = self.planning_output.plan

        content = f"""
\subsection*{{Datasets}}

We evaluate on {', '.join(plan.datasets)}.

\subsection*{{Baselines}}

We compare against the following baselines:

"""
        for baseline in plan.baseline_methods[:3]:
            content += f"- {baseline}\n"

        content += f"""

\subsection*{{Metrics}}

We use the following evaluation metrics:
"""
        for metric in plan.metrics:
            content += f"- {metric.name}: {metric.description}\n"

        content += f"""

\subsection*{{Setup}}

We run all experiments with 3 random seeds ({self.planning_output.random_seeds}) to ensure statistical robustness.
"""

        return content

    def _generate_results(self) -> str:
        """Generate results section."""
        content = "\subsection*{Main Results}\n\n"

        for result in self.experiment_output.results:
            mean_str = f"{result.mean:.4f}"
            std_str = f"{result.std:.4f}"
            sig_str = "*" if result.significant else ""

            content += f"Our method achieves {mean_str} ± {std_str} {sig_str} on {result.metric_name}.\n\n"

        if self.experiment_output.results and self.experiment_output.results[0].baseline_mean:
            baseline = self.experiment_output.results[0].baseline_mean
            content += f"Compared to the baseline of {baseline:.4f}, our method shows "
            if self.experiment_output.results[0].significant:
                content += "statistically significant improvement.\n"
            else:
                content += "comparable performance.\n"

        content += "\n\subsection*{Ablation Studies}\n\n"
        for result in self.experiment_output.ablation_results:
            config = result.metric_name.replace("_accuracy", "").replace("_", " ")
            content += f"- {config}: {result.mean:.4f} ± {result.std:.4f}\n"

        return content

    def _generate_discussion(self) -> str:
        """Generate discussion section."""
        conclusions = self.experiment_output.conclusions

        content = "Our experiments demonstrate several key findings:\n\n"

        for i, conc in enumerate(conclusions, 1):
            content += f"{i}. {conc}\n"

        content += "\n\subsection*{Limitations}\n\n"
        content += "Our study has several limitations:\n"
        content += "- Limited to specific datasets\n"
        content += "- Computational requirements may be high for some settings\n"
        content += "- Results may vary with different random seeds\n"

        return content

    def _generate_conclusion(self) -> str:
        """Generate conclusion section."""
        return """
We presented a novel approach for addressing the research question.
Our experimental results demonstrate the effectiveness of the proposed method.
Ablation studies confirm the importance of key components.

Future work includes:
\begin{itemize}
    \item Scaling to larger datasets
    \item Exploring different architectures
    \item Investigating theoretical guarantees
\end{itemize}
"""

    def _generate_citations(self, idea: CandidateIdea) -> list[Citation]:
        """Generate citations from related work."""
        citations = []

        if idea.related_work:
            for rw in idea.related_work[:10]:
                key = "".join(rw.authors[0].split()[-1:]) + str(rw.year or "") if rw.authors else f"ref{rw.year or 0}"
                citations.append(
                    Citation(
                        key=key,
                        title=rw.title,
                        authors=rw.authors,
                        year=rw.year,
                        venue="arXiv",
                        url=f"https://arxiv.org/abs/{rw.arxiv_id}" if rw.arxiv_id else None,
                    )
                )

        # Add baseline citations
        citations.extend([
            Citation(key="breiman2001", title="Random Forests", authors=["L. Breiman"], year=2001),
            Citation(key="he2016", title="Deep Residual Learning for Image Recognition", authors=["K. He", "X. Zhang", "S. Ren", "J. Sun"], year=2016, venue="CVPR"),
            Citation(key="dosovitskiy2020", title="An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale", authors=["A. Dosovitskiy", "L. Beyer", "A. Kolesnikov"], year=2020, venue="ICLR"),
        ])

        return citations

    def _generate_tables(self) -> list[str]:
        """Generate LaTeX tables for results."""
        tables = []

        # Main results table
        table = r"\begin{table}[ht]" + "\n"
        table += r"\centering" + "\n"
        table += r"\begin{tabular}{lccc}" + "\n"
        table += r"\toprule" + "\n"
        table += r"Method & Accuracy & F1-Score & \\" + "\n"
        table += r"\midrule" + "\n"

        for result in self.experiment_output.results:
            if "accuracy" in result.metric_name.lower():
                table += f"Our Method & ${result.mean:.4f} \\pm {result.std:.4f}$ & - & \\\\\n"

        if self.experiment_output.results and self.experiment_output.results[0].baseline_mean:
            table += f"Baseline & {self.experiment_output.results[0].baseline_mean:.4f} & - & \\\\\n"

        table += r"\bottomrule" + "\n"
        table += r"\end{tabular}" + "\n"
        table += r"\caption{Main results. Best results in bold.}" + "\n"
        table += r"\end{table}" + "\n"

        tables.append(table)

        return tables

    def _generate_latex(
        self,
        sections: list[PaperSection],
        citations: list[Citation],
        idea: CandidateIdea,
    ) -> str:
        """Generate full LaTeX document."""
        section_texts = {s.name: s.content for s in sections}

        return _LATEX_TEMPLATE.format(
            title=idea.title if idea else "Research Paper",
            abstract=self._generate_abstract(idea),
            introduction=section_texts.get("Introduction", ""),
            related_work=section_texts.get("Related Work", ""),
            methodology=section_texts.get("Methodology", ""),
            experiments=section_texts.get("Experiments", ""),
            results=section_texts.get("Results", ""),
            discussion=section_texts.get("Discussion", ""),
            conclusion=section_texts.get("Conclusion", ""),
        )

    def _compile_pdf(self, latex_source: str) -> Optional[str]:
        """Attempt to compile LaTeX to PDF."""
        tex_path = self.project.writing_dir / "paper.tex"
        output_dir = self.project.writing_dir

        try:
            # Check if pdflatex is available
            result = subprocess.run(
                ["which", "pdflatex"],
                capture_output=True,
                timeout=5,
            )
            if result.returncode != 0:
                return None

            # Write temporary tex file
            with open(tex_path, "w") as f:
                f.write(latex_source)

            # Run pdflatex
            result = subprocess.run(
                ["pdflatex", "-interaction=nonstopmode", "-output-directory", str(output_dir), str(tex_path)],
                capture_output=True,
                timeout=60,
                cwd=str(output_dir),
            )

            pdf_path = output_dir / "paper.pdf"
            if pdf_path.exists():
                return str(pdf_path)

        except Exception as e:
            self._log("compile_pdf", {"error": str(e)})

        return None

    def _generate_markdown(
        self,
        sections: list[PaperSection],
        tables: list[str],
        citations: list[Citation],
    ) -> str:
        """Generate markdown version of paper."""
        md = f"# {sections[0].title if sections else 'Research Paper'}\n\n"

        for section in sections:
            md += f"## {section.name}\n\n"
            md += section.content + "\n\n"

        if tables:
            md += "## Tables\n\n"
            for i, table in enumerate(tables, 1):
                md += f"### Table {i}\n\n"
                md += "```latex\n"
                md += table + "\n"
                md += "```\n\n"

        if citations:
            md += "## References\n\n"
            for cite in citations:
                authors = ", ".join(cite.authors[:3]) if cite.authors else "Unknown"
                year = cite.year or "N/A"
                md += f"- [{cite.key}] {authors} ({year}). {cite.title}\n"

        return md

    def _run_quality_checks(
        self,
        latex_source: str,
        tables: list[str],
        citations: list[Citation],
    ) -> dict[str, bool]:
        """Run quality checks on the paper."""
        checks = {}

        # Number verification - extract numbers from latex
        numbers_in_paper = set(re.findall(r'\d+\.?\d*', latex_source))
        checks["has_quantitative_results"] = len(numbers_in_paper) > 5

        # Citation check
        cited_keys = set(re.findall(r'\\cite\{([^}]+)\}', latex_source))
        available_keys = {c.key for c in citations}
        checks["all_citations_valid"] = cited_keys.issubset(available_keys) or len(cited_keys) == 0

        # LaTeX syntax check (basic)
        checks["latex_balanced_braces"] = latex_source.count("{") == latex_source.count("}")

        # Section presence
        required_sections = ["Introduction", "Related Work", "Methodology", "Experiments", "Results", "Conclusion"]
        checks["all_sections_present"] = all(
            s.lower() in latex_source.lower() for s in required_sections
        )

        return checks

    def _generate_review_comments(self, checks: dict[str, bool]) -> list[str]:
        """Generate review comments based on quality checks."""
        comments = []

        if not checks.get("all_sections_present", False):
            comments.append("Warning: Some required sections may be missing")

        if not checks.get("all_citations_valid", True):
            comments.append("Warning: Some citations may be invalid")

        if not checks.get("has_quantitative_results", True):
            comments.append("Warning: Limited quantitative results found")

        if not comments:
            comments.append("Paper structure looks good")

        return comments
